# Debian/Buster et others
# packages
---
backend: apt
update_db: false
checkupdates: false

operations:
- try_remove:
  - calamares
  - live-boot
  - live-boot-doc
  - live-boot-initramfs-tools
  - live-tools
  - penguins-eggs
  
