/Gtk/ButtonImages               true
/Gtk/CanChangeAccels            false
/Gtk/ColorPalette               black:white:gray50:red:purple:blue:light blue:green:yellow:orange:lavender:brown:goldenrod4:dodger blue:pink:light green:gray10:gray30:gray75:gray90
/Gtk/CursorThemeName            Tradicion
/Gtk/CursorThemeSize            0
/Gtk/DecorationLayout           menu:minimize,maximize,close
/Gtk/FontName                   Segoe UI This 10
/Gtk/IconSizes                  
/Gtk/KeyThemeName               
/Gtk/MenuBarAccel               F10
/Gtk/MenuImages                 true
/Gtk/MonospaceFontName          Monospace 10
/Gtk/ToolbarIconSize            3
/Gtk/ToolbarStyle               icons
/Net/CursorBlink                true
/Net/CursorBlinkTime            1200
/Net/DndDragThreshold           8
/Net/DoubleClickDistance        5
/Net/DoubleClickTime            400
/Net/EnableEventSounds          false
/Net/EnableInputFeedbackSounds  false
/Net/IconThemeName              Winbugs
/Net/SoundThemeName             default
/Net/ThemeName                  Windark
/Xft/Antialias                  -1
/Xft/Hinting                    -1
/Xft/HintStyle                  hintnone
/Xft/RGBA                       none
