/backdrop/screen0/monitor0/image-path                     /usr/share/images/desktop-base/default
/backdrop/screen0/monitor0/image-show                     true
/backdrop/screen0/monitor0/image-style                    5
/backdrop/screen0/monitor1/image-path                     /usr/share/images/desktop-base/default
/backdrop/screen0/monitor1/image-show                     true
/backdrop/screen0/monitor1/image-style                    5
/backdrop/screen0/monitor2/image-path                     /usr/share/images/desktop-base/desktop-background
/backdrop/screen0/monitor2/image-show                     true
/backdrop/screen0/monitor2/image-style                    5
/backdrop/screen0/monitor3/image-path                     /usr/share/images/desktop-base/desktop-background
/backdrop/screen0/monitor3/image-show                     true
/backdrop/screen0/monitor3/image-style                    5
/backdrop/screen0/monitorVirtual1/workspace0/color-style  1
/backdrop/screen0/monitorVirtual1/workspace0/image-style  5
/backdrop/screen0/monitorVirtual1/workspace0/last-image   /usr/share/backgrounds/Tempera_Noelia_Gerbaudo.jpg
/backdrop/screen0/monitorVirtual1/workspace1/color-style  1
/backdrop/screen0/monitorVirtual1/workspace1/image-style  5
/backdrop/screen0/monitorVirtual1/workspace1/last-image   /usr/share/images/desktop-base/Tempera_Pro_Noche.jpg
/backdrop/screen0/monitorVirtual1/workspace2/color-style  1
/backdrop/screen0/monitorVirtual1/workspace2/image-style  5
/backdrop/screen0/monitorVirtual1/workspace2/last-image   /usr/share/images/desktop-base/Tempera_Pro_Noche.jpg
/backdrop/screen0/monitorVirtual1/workspace3/color-style  1
/backdrop/screen0/monitorVirtual1/workspace3/image-style  5
/backdrop/screen0/monitorVirtual1/workspace3/last-image   /usr/share/images/desktop-base/Tempera_Pro_Noche.jpg
/desktop-icons/file-icons/show-filesystem                 false
/desktop-icons/file-icons/show-home                       true
/desktop-icons/file-icons/show-removable                  false
/desktop-icons/file-icons/show-trash                      true
/desktop-icons/icon-size                                  48
/desktop-icons/style                                      2
/desktop-icons/tooltip-size                               64,000000
/desktop-menu/show                                        false
/last/window-height                                       610
/last/window-width                                        722
